---
- name: Interface wireguard
  community.routeros.api_modify:
    path: interface wireguard
    data: "{{ routeros_interface_wireguard }}"
    handle_absent_entries: remove
  when: routeros_interface_wireguard is not none

- name: Interface wireguard peers
  community.routeros.api_modify:
    path: interface wireguard peers
    data: "{{ routeros_interface_wireguard_peers }}"
    handle_absent_entries: remove
  when: routeros_interface_wireguard_peers is not none
